### ISSUE TITLE
Assignee not stored

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/catalog#11]
When filling out a data request in the Web GUI, the field assignee reverts to the default setting of achtnits

**Comment by baloola** [comment]
The assignees list is simply the FAIRiCUBE organization members list on GitHub, sorted alphabetically. Hence the first item in this case is achnits ( it is not selected though).

**Comment by KathiSchleidt** [comment]
I get the alphabetic bit, also get that achtnits is just the first entry of the list. The problem is when one selects a different assignee, this doesn't get saved. When I edit again, this information is no longer visible, back to achtnits

**Comment by baloola** [comment]
I see, I will invistigate, in the mean time, one can assigne users directly in github

**Comment by baloola** [comment]
this issue should be fixed now, selecting an assignee should work now.

**Comment by KathiSchleidt** [comment]
Thanks!
