### ISSUE TITLE
Delete Record?

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/catalog#12]
I've just noticed an unplanned duplicate record, we have 2 entries for ERA5_monthly_averaged_data, this is a mistake.
How can we delete a record from the WebGUI?

**Comment by baloola** [comment]
some user is re-adding ERA5_monthly_averaged_data instead of editing it.

**Comment by KathiSchleidt** [comment]
Yes, that's the background of this request, @Susannaioni accidentally created 2 duplicates. Thus the question of how to delete such inadvertent entries

**Comment by baloola** [comment]
I did not add a delete feature to the GUI, this has to be done manually in github for now.

**Comment by Susannaioni** [comment]
@baloola yes, it was me. I think I double clicked on submit while it was loading and it created a double request.

**Comment by baloola** [comment]
@Susannaioni no problem, just let me know which pr needs to be removed ( link here ).
Thank you.

**Comment by Susannaioni** [comment]
@baloola Thank you. It's this one https://github.com/FAIRiCUBE/data-requests/pull/269

**Comment by baloola** [comment]
closed as the entry was deleted
