### ISSUE TITLE
Organization roles

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/catalog#16]
@baloola As discussed yesterday, please add a role to the Organizations section of the metadata GUI.

Example of possible role codes from ISO 19115, maybe propose a subset:
![grafik](https://github.com/FAIRiCUBE/catalog/assets/11915304/72716da3-61ba-4539-a468-e60fea219974)

**Comment by baloola** [comment]
added roles according to [stsc-spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object)
![Screenshot 2024-06-24 19:39:05](https://github.com/FAIRiCUBE/catalog/assets/28819736/c0dfcf9a-038e-4166-8dbd-8d7c4446ba68)

**Comment by KathiSchleidt** [comment]
Thanks!
