### ISSUE TITLE
Automatically add band names to Keywords

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/catalog#22]
The Observable Property or Variable being conveyed by a dataset is an essential search criterion. At present, it's nested under the band information of the Coverage. To make search easier, it would be valuable to have these Variable names available via the STAC Keywords.

As this should be human readable, we'd need to use the name of the band for this (the vocabulary links in the definition are also valuable, but not in Keywords). From what I can see, this has received the strange name "cell components", should be changed to label in the WebGUI. 

Please add the band labels to the Keywords.

**Comment by baloola** [comment]
submitting a form with bands, should automatically add band names to keywords ( the addition happens after submission)

**Comment by KathiSchleidt** [comment]
Thanks!
