### ISSUE TITLE
Indicate Mandatory Fields in WebGUI

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/catalog#27]
We're receiving complaints from UC partners that they cannot see which fields are mandatory when entering metadata in the WebGUI. Please update this. Cardinalities are clear in #9

**Comment by baloola** [comment]
an update was released, now editor frontend showing messages that inform users about messing fields, while submission will work validation will fail. (there are still required fields for submission -e.g id-)
![Screenshot from 2024-07-17 18-47-26](https://github.com/user-attachments/assets/952a0261-8705-4579-9db1-2b3d8e868937)

**Comment by misev** [comment]
An issue sort of caused by this change is #30, where the resolution of an irregular axis is a mandatory field.

**Comment by KathiSchleidt** [comment]
Works!
