### ISSUE TITLE
How to delete entries in the catalog editor?

### ISSUE THREAD

**Issue by misev** [FAIRiCUBE/catalog#28]
Some entries in the catalog editor are outdated and it would be good to be able to delete them to clean up and avoid confusion, e.g. "Global_Pesticide_Grids_PESTCHEMGRIDS,_v1.01". How can they be deleted?

**Comment by baloola** [comment]
Entries has to be deleted manually from github, ( closeing the PR + deleting the related branch ).
Would like me to delete https://github.com/FAIRiCUBE/data-requests/pull/259  entry ?

**Comment by misev** [comment]
Thanks, that works.
